---
title: "Resume"
#output:
  # html_document:
  #   toc: true  # make a table of contents
  #   toc_float: true  # table of contents as sidebar
---

<center>
<font size="12">
Carmen Galaz-García
</font>
</center>

<br>


Location: Santa Barbara, CA           

e-mail: carmengg@math.ucsb.edu

<br>



## SUMMARY

PhD candidate seeking to leverage her analytic knowledge and coding experience in an interdisciplinary working group that creates and implements solutions to environmental issues.

* 5+ years of experience in mathematical research and higher education.

* Experience using R and Python, with background in computer algorithms and object oriented programming. 

* Excellent public speaking and teaching skills, both with specialized audiences and in scientific outreach. Received teaching awards from the UCSB Mathematics Department and Graduate Student Association.

* Effective team-work and leadership skills developed through founding the Mathematics Directed Reading Program impacting 120+ graduate and undergraduate students.

* Strong interest in ecological restoration and habitat management projects, fostered by exploring and learning about California’s ecosystems and wildlife.
<br>


## EDUCATION

**Ph.D. in Mathematics**   (Expected July 2021)

**University of California, Santa Barbara **

* Relevant courses: Introduction to Environmental Data Science & Statistics, Advanced Data Analysis, Introduction to Ecological Restoration at UCSB’s North Campus Open Space

<br>

**B.Sc. in Mathematics**  (June 2015)

**Universidad de Guanajuato, México**

* Study abroad semester: Uppsala University, Sweden

<br> 

## RESEARCH EXPERIENCE


**University of California, Santa Barbara**, CA    (June 2017 - present)

*Graduate Researcher at the Mathematics Department*

* Worked independently to design research projects, met advisor weekly for progress updates, met deadlines. 

* Created a Python library to perform hyperbolic calculations and search for hyperbolic groups.

*  My research has resulted in two single-authored manuscripts (one submitted for publication), 3 presenta- tions at national conferences and research seminar invitations to MIT, Tufts U, Temple U & Arizona State U.


<br>

*Student at Bren School of Environmental Science & Management*   (October 2020 - present) 

* Proficient in the use of the tidyverse R library for data wrangling, statistical analysis and visualization.

* Assessed the fitness of statistical models for different types of real world data.

* Comfortable using git and GitHub for version control, repository usage and collaboration.

<br>

**University of California, Davis**, CA 

*Fulbright Scholarship, Summer Undergraduate Researcher*    (Summer 2014)

* Collaborated with computer scientists and mathematicians in developing geometric combinatorial tools.

<br>

## SKILLS AND INTERESTS


**Programming & software:** Python, R, C++, LaTeX, GitHub 

**Languages:** Spanish (native), English (fluent), French (intermediate)

**Interests:** Hiking, yoga, bird watching. Member of the Goleta Coast Audubon Society and the Santa Barbara Audubon Society

<br>

## LEADERSHIP EXPERIENCE


**Mathematics Directed Reading Program at UCSB (DRP)**

*Co-founder, Organizer and Mentor*   (2018-2020)

* Secured funding from the DRP National Network to start the UCSB DRP.

* Coordinated the application process and selection of participants. In 2020 we received 120+ applications to participate, doubling the number of applications in 2019.

* Mentored undergraduates in reading advanced mathematics and helped them design and present a poster showcasing their work.

<br>

**Institute for Advanced Studies**

*Women and Mathematics Ambassador*   (2017-2018)

* Obtained a grant from the Institute for Advanced Study to implement a program aimed to showcase the achievements of women in mathematics.

* Worked with a team to design and host 15 public events at the UCSB Mathematics Department. These included panels, workshops, research talks and social events.

* Managed funding and worked in close contact with administrative staff.

<br>


## TEACHING EXPERIENCE


**University of California, Santa Barbara**, CA

*Instructor of Record*    (Summer 2018, 2019, 2020)

* Taught Calculus for Social and Environmental Science twice and Differential Calculus once. Each course lasted 6 weeks and had 40 students.

* Designed goals and tasks to help students master the subject and use it in the context of their majors.

* Provided grading, individual feedback and motivation to students, often through virtual platforms.

* Received Excellence in Teaching Award Honorable Mention from the UCSB Graduate Student Association.

<br>

*Teaching Assistant September*    (2015 - present)

* Led review and discussion sessions for over 15 undergraduate mathematics courses, ranging from lower division courses with 100 students to specialized topics classes for small groups.

* Received Outstanding Teaching Assistant Award from the UCSB Mathematics Department.

<br>

**Summer Institute in Mathematics and Science,
Center for Science and Engineering Partnerships**, CA

*Lead Mathematics Instructor*   (Summer 2020)

* Collaborated in the design of the program’s virtual mathematics courses.

* Recruited and oriented two more mathematics instructors for the SIMS program.

* Facilitated communication between the mathematics instructors and the program organizers.

<br>


## MENTORING & OUTREACH


**Mathematics Department, UCSB**   (2018- 2020)

* Invited panelist for 6 events about teaching best practices, graduate student life and academic achievement.
Association for Women in Mathematics, UCSB chapter 2018- 2020 

* Co-organizer and instructor in a STEM outreach event for middle school students.

* Gave a one-hour workshop about geometry and combinatorics for 15 elementary school kids.

* Gave two talk about my research to 30 mathematics majors, one in UCSB and one at my Universidad de Guanajuato, Mexico. 